# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "GMT"
    registries: '*'
    open-pull-requests-limit: 3

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "GMT"
    registries: '*'
    open-pull-requests-limit: 3

  - package-ecosystem: "nuget"
    directory: "/AutomationTest"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "GMT"
    registries: '*'
    open-pull-requests-limit: 3