apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hsd-oauth-proxy-externalsecret
spec:
  secretStoreRef:
    name: aws-parameter-cluster-store
    kind: ClusterSecretStore
  refreshInterval: "10m"
  target:
    name: hsd-oauth-proxy-externalsecret
    creationPolicy: 'Owner' 
  dataFrom:
  - extract:
     key: {{ .Values.secretStoreBasePath}}/authgateway/oauthproxy-secrets
  - extract:
     key: {{ .Values.secretStoreBasePath}}/authgateway/oauth-cookiedomain-env
  - extract:
     key: {{ .Values.secretStoreBasePath}}/authgateway/oauth-whitelistdomain-env