apiVersion: v1
kind: Service
metadata:
  name: {{ include "hsd-oauth-proxy.fullname" . }}
  labels:
    {{- include "hsd-oauth-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
    {{- end }}
    
  selector:
    {{- include "hsd-oauth-proxy.selectorLabels" . | nindent 4 }}
